site_name: Tabular SSL Documentation
site_description: Documentation for the Tabular SSL library
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed
  - admonition
  - footnotes
  - meta
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Tutorials:
    - tutorials/index.md
    - tutorials/getting-started.md
    - tutorials/basic-usage.md
  - How-to Guides:
    - how-to-guides/index.md
    - how-to-guides/data-preparation.md
    - how-to-guides/model-training.md
    - how-to-guides/evaluation.md
  - Reference:
    - reference/index.md
    - reference/api.md
    - reference/models.md
    - reference/data.md
    - reference/utils.md
  - Explanation:
    - explanation/index.md
    - explanation/architecture.md
    - explanation/ssl-methods.md
    - explanation/performance.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            show_category_heading: true
            show_if_no_docstring: true 