# Autoencoder Event Encoder Configuration
# Autoencoder-based event encoder for self-supervised learning

_target_: tabular_ssl.models.components.AutoEncoderEventEncoder

input_dim: 64
hidden_dims: [128, 64]
latent_dim: 32
dropout: 0.1
use_batch_norm: false 