# Contrastive Event Encoder Configuration
# Contrastive learning-based event encoder

_target_: tabular_ssl.models.components.ContrastiveEventEncoder

input_dim: 64
hidden_dims: [128, 256]
output_dim: 512
temperature: 0.1
dropout: 0.1 