_target_: tabular_ssl.models.components.CategoricalEmbedding

# Example configuration - should be overridden by datamodule
vocab_sizes:
  feature_1: 10
  feature_2: 20
embedding_dims:
  feature_1: 32
  feature_2: 64 