defaults:
  - _self_
  - event_encoder: mlp
  - sequence_encoder: transformer
  - embedding: categorical
  - projection_head: mlp
  - prediction_head: classification

_target_: tabular_ssl.models.base.BaseModel

# Training configuration
learning_rate: 1.0e-4
weight_decay: 0.01
optimizer_type: adamw  # adamw, adam, sgd
scheduler_type: cosine  # cosine, step, plateau, null 