wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  project: tabular-ssl
  name: ${name}
  save_dir: ${paths.output_dir}
  offline: false
  log_model: false
  tags: ${tags}
  job_type: train 