# Project paths configuration

# Root directory - fallback to current directory if PROJECT_ROOT not set
root_dir: ${oc.env:PROJECT_ROOT,.}

# Data directory
data_dir: ${paths.root_dir}/data

# Logs directory  
log_dir: ${paths.root_dir}/logs

# Output directory (created by Hydra)
output_dir: ${hydra:runtime.output_dir}

# Working directory
work_dir: ${hydra:runtime.cwd} 