# RNN Sequence Encoder Configuration
# LSTM/GRU-based sequence encoding

_target_: tabular_ssl.models.components.RNNSequenceEncoder

input_dim: 512
hidden_dim: 256
num_layers: 2
rnn_type: lstm  # lstm, gru, rnn
dropout: 0.1
bidirectional: false 