# @package _global_

# Main configuration file for tabular-ssl
defaults:
  - _self_
  - data: default
  - model: default
  - trainer: default
  - callbacks: default
  - paths: default
  - hydra: default
  - logger: null  # Set via command line: python train.py logger=wandb
  - experiment: null  # Set via command line: python train.py experiment=transformer_small

# Task settings
task_name: train
seed: 42

# Run settings  
name: ${now:%Y-%m-%d_%H-%M-%S}
tags: ["dev"]

# Mode flags
train: true
test: false
debug: false

# Optional settings
print_config: true
ignore_warnings: false 