# @package _global_

# Simplified main configuration for tabular-ssl
defaults:
  - _self_
  - model: default  # Model configurations in single file
  - data: default   # Data configurations in single file
  - training: default  # All training-related configs in one place
  - experiment: null  # Optional experiment overrides

# Basic settings
task_name: "tabular_ssl"
seed: 42
name: "${now:%Y-%m-%d_%H-%M-%S}"

# Mode flags
train: true
test: false
debug: false

# Optional settings
print_config: true
ignore_warnings: false

# Root paths (simplified)
paths:
  root_dir: ${oc.env:PROJECT_ROOT,"."}
  data_dir: ${paths.root_dir}/data
  log_dir: ${paths.root_dir}/logs
  output_dir: ${paths.root_dir}/outputs
  work_dir: ${paths.root_dir}

# Logging (simplified - no separate config files)
logger:
  _target_: pytorch_lightning.loggers.CSVLogger
  save_dir: ${paths.log_dir}/csv
  name: ${name}

# Hydra configuration (simplified)
hydra:
  sweep:
    dir: ${paths.output_dir}/multirun
    subdir: ${hydra.job.num}
  run:
    dir: ${paths.output_dir}/run
  job_logging:
    handlers:
      file:
        filename: ${hydra:runtime.output_dir}/hydra.log 