# ReConTab Corruption Strategy Configuration
# Multi-task reconstruction-based learning

_target_: tabular_ssl.models.components.ReConTabCorruption

# Base corruption rate for masking
corruption_rate: 0.15

# Feature type specification (auto-detected if null)
categorical_indices: null
numerical_indices: null

# Types of corruption to apply
corruption_types: ["masking", "noise", "swapping"]

# Masking strategy: "random", "column_wise", or "block"
masking_strategy: "random"

# Noise injection parameters
noise_std: 0.1

# Feature swapping parameters
swap_probability: 0.1

# Reconstruction loss weights
reconstruction_weights:
  masked_reconstruction: 1.0
  denoising: 0.5
  unswapping: 0.3

# Advanced options
block_size_ratio: 0.15  # For block masking strategy
column_corruption_prob: 0.3  # For column-wise masking 