# SCARF Corruption Strategy Configuration
# Self-Supervised Contrastive Learning using Random Feature Corruption

_target_: tabular_ssl.models.components.SCARFCorruption

# Corruption parameters
corruption_rate: 0.6

# Corruption strategy: "random_swap" or "marginal_sampling"
corruption_strategy: "random_swap"

# Contrastive learning parameters
temperature: 0.1  # Temperature for contrastive loss
projection_dim: 128  # Dimension of projection head for contrastive learning

# Training parameters
use_momentum_encoder: false  # Whether to use momentum encoder (like MoCo)
momentum: 0.999  # Momentum coefficient if using momentum encoder 