# VIME Corruption Strategy Configuration
# Value Imputation and Mask Estimation

_target_: tabular_ssl.models.components.VIMECorruption

# Corruption parameters
corruption_rate: 0.3

# Feature type specification (auto-detected if null)
categorical_indices: null
numerical_indices: null

# Vocabulary sizes for categorical features (auto-detected if null)
categorical_vocab_sizes: null

# Statistical distributions for numerical features (auto-detected if null)  
numerical_distributions: null

# VIME-specific parameters
mask_estimation_weight: 1.0  # Weight for mask estimation loss
value_imputation_weight: 1.0  # Weight for value imputation loss 